package algoritmosRecursivos;

//PUBLIC INTERFACE NODE<T> {
//    PUBLIC BOOLEAN EQUALS(K KEY);
//    PUBLIC NODE<T> NEXT();
//}
//
////ASSUMINDO QUE O MÉTODO EQUALS() RETORNA VERDADEIRO PARA A CHAVE QUE REPERESENTA O OBJETO ARMAZENADO EM UM NODE, E FALSO CASO CONTRÁRIO, 
////IMPLEMENTE, UTILIZANDO UM ALGORITMO RECURSIVO, O METODO SEARCH(), NA CLASSE LINKEDLIST:
//
//CLASS LINKEDLIST<T> {
//    PRIVATE NODE<T> HEAD;
//
//    PUBLIC NODE<T> SEARCH(K KEY) {
//        // SEU CÓDIGO...
//    }
//    
//}